# Generated by Django 5.2.8 on 2025-11-22 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('breed_id', models.AutoField(primary_key=True, serialize=False)),
                ('breed_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('med_id', models.AutoField(primary_key=True, serialize=False)),
                ('med_name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=50, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('stock_qty', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('treatment_id', models.AutoField(primary_key=True, serialize=False)),
                ('treatment_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('vaccine_id', models.AutoField(primary_key=True, serialize=False)),
                ('vaccine_name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('vet_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('animal_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.breed')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.owner')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.status')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.CharField(blank=True, max_length=500, null=True)),
                ('procedure_note', models.TextField(blank=True, null=True)),
                ('cost', models.IntegerField(default=0)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.animal')),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.veterinarian')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.medication')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treat_date', models.DateTimeField()),
                ('note', models.TextField(blank=True, null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.medicalrecord')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.treatment')),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vac_date', models.DateField()),
                ('next_vac_date', models.DateField(blank=True, null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.medicalrecord')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hospital.vaccination')),
            ],
        ),
    ]
