# Generated by Django 5.2.8 on 2025-12-16 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='업체명')),
                ('contact', models.CharField(max_length=50, verbose_name='연락처')),
                ('item_type', models.CharField(help_text='예: 약품, 의료기기, 소모품', max_length=100, verbose_name='주요 납품 품목')),
            ],
        ),
        migrations.AddField(
            model_name='medicaltool',
            name='status',
            field=models.CharField(choices=[('normal', '정상 작동'), ('broken', '고장'), ('repairing', '수리중')], default='normal', max_length=20, verbose_name='기기 상태'),
        ),
        migrations.AlterField(
            model_name='medicaltool',
            name='code',
            field=models.CharField(blank=True, max_length=50, verbose_name='관리코드'),
        ),
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='품명')),
                ('stock', models.IntegerField(default=0, verbose_name='재고 수량')),
                ('unit', models.CharField(help_text='box, ea, roll', max_length=10, verbose_name='단위')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.vendor', verbose_name='거래처')),
            ],
        ),
    ]
