# Generated by Django 5.2.8 on 2025-12-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_vendor_medicaltool_status_alter_medicaltool_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumable',
            name='unit',
            field=models.CharField(max_length=10, verbose_name='단위'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='test_result',
            field=models.TextField(blank=True, verbose_name='검사 결과'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='description',
            field=models.TextField(blank=True, verbose_name='복용법'),
        ),
        migrations.AlterField(
            model_name='toolusage',
            name='count',
            field=models.IntegerField(default=1, verbose_name='사용 수량'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='item_type',
            field=models.CharField(max_length=100, verbose_name='주요 납품 품목'),
        ),
    ]
